
export type RequirementStatus = 'not-started' | 'in-progress' | 'review' | 'completed';

export interface ISORequirement {
  id: string;
  number: string;
  title: string;
  description: string;
  status: RequirementStatus;
  progress: number;
  children?: ISORequirement[];
}

export const isoRequirements: ISORequirement[] = [
  {
    id: 'context',
    number: '4',
    title: 'Context of the Organization',
    description: 'Understanding the organization and its context, interested parties, and establishing the QMS scope.',
    status: 'not-started',
    progress: 0,
    children: [
      {
        id: 'context-org',
        number: '4.1',
        title: 'Understanding the organization and its context',
        description: 'Determine external and internal issues relevant to the organization\'s purpose and strategic direction.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'context-parties',
        number: '4.2',
        title: 'Understanding the needs and expectations of interested parties',
        description: 'Determine interested parties and their requirements relevant to the QMS.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'context-scope',
        number: '4.3',
        title: 'Determining the scope of the quality management system',
        description: 'Determine boundaries and applicability of the QMS to establish its scope.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'context-qms',
        number: '4.4',
        title: 'Quality management system and its processes',
        description: 'Establish, implement, maintain and continually improve the QMS.',
        status: 'not-started',
        progress: 0,
      },
    ],
  },
  {
    id: 'leadership',
    number: '5',
    title: 'Leadership',
    description: 'Demonstrating leadership commitment, establishing policy, and assigning roles and responsibilities.',
    status: 'not-started',
    progress: 0,
    children: [
      {
        id: 'leadership-commitment',
        number: '5.1',
        title: 'Leadership and commitment',
        description: 'Top management shall demonstrate leadership and commitment to the QMS.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'leadership-policy',
        number: '5.2',
        title: 'Policy',
        description: 'Establish, implement and maintain a quality policy appropriate to the organization.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'leadership-roles',
        number: '5.3',
        title: 'Organizational roles, responsibilities and authorities',
        description: 'Ensure responsibilities and authorities are assigned, communicated and understood.',
        status: 'not-started',
        progress: 0,
      },
    ],
  },
  {
    id: 'planning',
    number: '6',
    title: 'Planning',
    description: 'Addressing risks and opportunities, establishing quality objectives, and planning changes.',
    status: 'not-started',
    progress: 0,
    children: [
      {
        id: 'planning-risks',
        number: '6.1',
        title: 'Actions to address risks and opportunities',
        description: 'Determine risks and opportunities that need to be addressed to ensure the QMS can achieve intended results.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'planning-objectives',
        number: '6.2',
        title: 'Quality objectives and planning to achieve them',
        description: 'Establish quality objectives at relevant functions, levels and processes.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'planning-changes',
        number: '6.3',
        title: 'Planning of changes',
        description: 'When changes to the QMS are needed, they shall be carried out in a planned manner.',
        status: 'not-started',
        progress: 0,
      },
    ],
  },
  {
    id: 'support',
    number: '7',
    title: 'Support',
    description: 'Providing resources, ensuring competence, promoting awareness, and controlling documented information.',
    status: 'not-started',
    progress: 0,
    children: [
      {
        id: 'support-resources',
        number: '7.1',
        title: 'Resources',
        description: 'Determine and provide resources needed for the establishment, implementation, maintenance and continual improvement of the QMS.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'support-competence',
        number: '7.2',
        title: 'Competence',
        description: 'Determine necessary competence, ensure competence is acquired, and take actions to acquire necessary competence.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'support-awareness',
        number: '7.3',
        title: 'Awareness',
        description: 'Ensure persons doing work under the organization\'s control are aware of the quality policy, objectives, their contribution, and implications of nonconformity.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'support-communication',
        number: '7.4',
        title: 'Communication',
        description: 'Determine internal and external communications relevant to the QMS.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'support-documented-info',
        number: '7.5',
        title: 'Documented information',
        description: 'The QMS shall include documented information required by ISO 9001 and determined by the organization as necessary for the effectiveness of the QMS.',
        status: 'not-started',
        progress: 0,
      },
    ],
  },
  {
    id: 'operation',
    number: '8',
    title: 'Operation',
    description: 'Planning and control of operations, defining requirements, designing products/services, and controlling external providers.',
    status: 'not-started',
    progress: 0,
    children: [
      {
        id: 'operation-planning',
        number: '8.1',
        title: 'Operational planning and control',
        description: 'Plan, implement and control processes needed to meet requirements for products and services.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'operation-requirements',
        number: '8.2',
        title: 'Requirements for products and services',
        description: 'Establish processes for communication with customers, determining requirements, and reviewing requirements.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'operation-design',
        number: '8.3',
        title: 'Design and development of products and services',
        description: 'Establish, implement and maintain a design and development process appropriate to ensuring subsequent provision of products and services.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'operation-external',
        number: '8.4',
        title: 'Control of externally provided processes, products and services',
        description: 'Ensure externally provided processes, products and services conform to requirements.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'operation-production',
        number: '8.5',
        title: 'Production and service provision',
        description: 'Implement production and service provision under controlled conditions.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'operation-release',
        number: '8.6',
        title: 'Release of products and services',
        description: 'Implement planned arrangements to verify product and service requirements have been met.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'operation-nonconforming',
        number: '8.7',
        title: 'Control of nonconforming outputs',
        description: 'Ensure outputs that do not conform to requirements are identified and controlled to prevent unintended use or delivery.',
        status: 'not-started',
        progress: 0,
      },
    ],
  },
  {
    id: 'performance',
    number: '9',
    title: 'Performance Evaluation',
    description: 'Monitoring, measuring, analyzing, evaluating, conducting internal audits, and management reviews.',
    status: 'not-started',
    progress: 0,
    children: [
      {
        id: 'performance-monitoring',
        number: '9.1',
        title: 'Monitoring, measurement, analysis and evaluation',
        description: 'Determine what needs to be monitored and measured, and methods for monitoring, measurement, analysis and evaluation.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'performance-audit',
        number: '9.2',
        title: 'Internal audit',
        description: 'Conduct internal audits at planned intervals to provide information on whether the QMS conforms to requirements and is effectively implemented and maintained.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'performance-review',
        number: '9.3',
        title: 'Management review',
        description: 'Top management shall review the organization\'s QMS at planned intervals to ensure its continuing suitability, adequacy, effectiveness and alignment with strategic direction.',
        status: 'not-started',
        progress: 0,
      },
    ],
  },
  {
    id: 'improvement',
    number: '10',
    title: 'Improvement',
    description: 'Identifying nonconformities, taking corrective actions, and continually improving the QMS.',
    status: 'not-started',
    progress: 0,
    children: [
      {
        id: 'improvement-general',
        number: '10.1',
        title: 'General',
        description: 'Determine and select opportunities for improvement and implement necessary actions.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'improvement-nonconformity',
        number: '10.2',
        title: 'Nonconformity and corrective action',
        description: 'When a nonconformity occurs, take action to control and correct it, and deal with the consequences.',
        status: 'not-started',
        progress: 0,
      },
      {
        id: 'improvement-continual',
        number: '10.3',
        title: 'Continual improvement',
        description: 'Continually improve the suitability, adequacy and effectiveness of the QMS.',
        status: 'not-started',
        progress: 0,
      },
    ],
  },
];
