
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuração segura - usar variáveis de ambiente
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Função para verificar se estamos em ambiente de desenvolvimento
const isDevelopment = import.meta.env.DEV;

// Configuração de fallback para desenvolvimento
const fallbackConfig = {
  url: 'https://kxkcgbtsgfyisbrtjmvv.supabase.co',
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4a2NnYnRzZ2Z5aXNicnRqbXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzODQ1MTQsImV4cCI6MjA1NDk2MDUxNH0.JHd7Cafdd4gxn7s_DE3ndeHiZ7Y-Om-c5M8J0POem0U'
};

// Usar credenciais do ambiente ou fallback
const supabaseUrl = SUPABASE_URL || fallbackConfig.url;
const supabaseKey = SUPABASE_PUBLISHABLE_KEY || fallbackConfig.key;

// Validação básica de formato
const isValidUrl = (url: string) => {
  try {
    new URL(url);
    return url.includes('supabase.co') || url.includes('localhost');
  } catch {
    return false;
  }
};

const isValidKey = (key: string) => {
  return key && key.length > 10 && key.startsWith('eyJ');
};

// Verificar se as credenciais são válidas
if (!isValidUrl(supabaseUrl) || !isValidKey(supabaseKey)) {
  console.error('SUPABASE CONFIG ERROR: Invalid credentials detected');
  if (!isDevelopment) {
    throw new Error('Invalid Supabase configuration');
  }
}

// Log de configuração (apenas em desenvolvimento)
if (isDevelopment) {
  console.log('Supabase client initialized:', {
    url: supabaseUrl.substring(0, 30) + '...',
    hasKey: !!supabaseKey,
    isProduction: !isDevelopment
  });
}

export const supabase = createClient<Database>(
  supabaseUrl, 
  supabaseKey,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false,
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      flowType: 'pkce'
    },
    db: {
      schema: 'public'
    },
    global: {
      headers: {
        'X-Client-Info': 'peter-ia'
      }
    }
  }
);

// Helper function to check if admin account exists
export const confirmAdminEmail = async (email: string) => {
  try {
    console.log("Checking admin account:", email);
    
    // Verificação segura sem bypass
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) {
      return { success: false, error: new Error("User not authenticated") };
    }
    
    // Verificar se o usuário atual tem permissões de admin
    const { data: profile, error: profileError } = await supabase
      .from('user_profiles')
      .select('is_super_admin, is_company_admin')
      .eq('id', user.id)
      .single();
    
    if (profileError || !profile) {
      return { success: false, error: new Error("Unable to verify admin status") };
    }
    
    if (!profile.is_super_admin && !profile.is_company_admin) {
      return { success: false, error: new Error("Insufficient permissions") };
    }
    
    return { success: true, data: user };
  } catch (error) {
    console.error("Unexpected error checking admin account:", error);
    return { success: false, error };
  }
};

// Função para testar a conexão
export const testConnection = async () => {
  try {
    const { data, error } = await supabase.from('connection_test').select('*').limit(1);
    return { success: !error, error };
  } catch (error) {
    return { success: false, error };
  }
};
